<template>
  <v-container style="max-width: 1700px;" fill-height>
    <h5 class="text-h5 text-md-h4 font-weight-bold text-center my-10 secondary">
      Admin Panel
    </h5>
    <v-row>
      <v-col cols="12" md="8">
        <section class="rounded shadow">
          <v-sheet>
            <v-table class="rounded-sm" style="margin-top: 0.5rem;">
              <thead class="bg-grey-lighten-5">
                <tr>
                  <th
                    class="text-grey-darken-1"
                    v-for="head in vouchersHeaders"
                    :key="head"
                  >
                    {{ head }}
                  </th>
                  <th class="text-grey-darken-1">
                    Approve/Reject
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(item, index) in usersPerPage" :key="index">
                  <td>{{ item.id }}</td>
                  <td v-if="item.name" class="d-flex align-center">
                    <v-avatar color="primary" size="30" class="mr-2">
                      <span class="text-uppercase">{{
                        addAvatar(item.name)
                      }}</span>
                    </v-avatar>
                    <div>
                      <p>{{ item.name }}</p>
                      <p>
                        {{ item.email }}
                      </p>
                    </div>
                  </td>

                  <td class="d-flex align-center" v-else>
                    <v-avatar color="warning" size="30" class="mr-2">
                      <span class="text-uppercase">A</span>
                    </v-avatar>
                    <div>
                      <p>Voucher generated by Admin</p>
                    </div>
                  </td>
                  <td v-if="item.reason">{{ item.reason }}</td>
                  <td v-else>-</td>
                  <td>{{ item.vms }}</td>
                  <td>{{ item.public_ips }}</td>
                  <td v-if="!item.approved && !item.rejected">
                    <BaseButton
                      color="primary"
                      text="Approve"
                      size="small"
                      class="mr-2 text-capitalize"
                      variant="flat"
                      @click="approveVoucher(item.id, true)"
                    />

                    <BaseButton
                      color="red-lighten-1"
                      text="Reject"
                      size="small"
                      class="text-capitalize"
                      variant="flat"
                      @click="approveVoucher(item.id, false)"
                    />
                  </td>
                  <td v-else-if="item.rejected">
                    <span class="text-error">Rejected</span>
                  </td>
                  <td v-else>
                    <span class="text-success">Approved</span>
                  </td>
                </tr>
              </tbody>
            </v-table>
            <div class="actions d-flex justify-center align-center">
              <v-pagination
                v-model="currentPage"
                :length="Math.ceil(totalPages / itemsPerPage)"
                :total-visible="Math.ceil(totalPages / itemsPerPage)"
              ></v-pagination>
              <BaseButton
                v-if="approveAllCount > 0"
                color="primary"
                text="Approve All"
                class="approve text-capitalize mr-5"
                @click="approveAllVouchers"
              />
            </div>
          </v-sheet>
        </section>
      </v-col>
      <v-col cols="12" md="4">
        <v-row>
          <v-col>
            <div
              class="resources text-white text-center rounded-lg bg-primary py-5 shadow"
            >
              <p>
                <strong style="font-size: 2.5rem;">{{ usedResources }}</strong>
              </p>
              <p class="mx-lg-auto font-weight-medium">
                Used VMs
              </p>
            </div>
          </v-col>
          <v-col>
            <div
              class="resources text-white text-center rounded-lg bg-primary py-5 shadow"
            >
              <p>
                <strong style="font-size: 2.5rem;">{{ usedIPs }}</strong>
              </p>
              <p class="mx-lg-auto font-weight-medium">
                Used IPs
              </p>
            </div>
          </v-col>
        </v-row>
        <section class="my-5 shadow">
          <v-sheet rounded class="bg-grey-lighten-5">
            <h5 class="text-grey-darken-1 text-h5 bg-primary text-center pa-4">
              Users
            </h5>
            <div v-if="users.length > 0">
              <v-table class="rounded-lg">
                <thead class="bg-grey-lighten-5">
                  <tr>
                    <th
                      class="text-grey-darken-1"
                      v-for="head in usersHeaders"
                      :key="head"
                    >
                      {{ head }}
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="(item, index) in users" :key="index">
                    <td>{{ ++index }}</td>
                    <td>{{ item.name }}</td>
                    <td>
                      {{ item.email }}
                    </td>
                    <td>
                      <span class="text-red">{{ item.used_vms }}</span
                      >/<span>{{ item.vms }}</span>
                    </td>
                    <td>
                      <span class="text-red">{{ item.used_public_ips }}</span
                      >/<span>{{ item.public_ips }}</span>
                    </td>
                  </tr>
                </tbody>
              </v-table>
            </div>
          </v-sheet>
        </section>
      </v-col>
    </v-row>
    <Toast ref="toast" />
  </v-container>
</template>

<script>
import { ref, onMounted, computed } from "vue";
import BaseButton from "@/components/Form/BaseButton.vue";
import userService from "@/services/userService.js";
import Toast from "@/components/Toast.vue";

export default {
  components: {
    BaseButton,
    Toast,
  },
  setup() {
    const confirm = ref(null);
    const vouchersHeaders = ref([
      "No",
      "User",
      "Reason for Voucher",
      "VMs",
      "Public IPs",
    ]);

    const usersHeaders = ref(["No", "Name", "Email", "VMs", "IPs"]);

    const vouchers = ref([]);
    const users = ref([]);
    const toast = ref(null);
    const loading = ref(false);
    const usedResources = ref(null);
    const usedIPs = ref(null);
    const approveAllCount = ref(null);
    const currentPage = ref(null);
    const totalPages = ref(null);
    const itemsPerPage = ref(null);
    const userInfo = ref(null);

    currentPage.value = 1;
    itemsPerPage.value = 10;

    const getVouchers = () => {
      userService
        .getVouchers()
        .then((response) => {
          const { data } = response.data;
          vouchers.value = data;
          totalPages.value = data.length;
          approveAllCount.value = 0;

          for (let voucher of data) {
            if (!voucher?.approved) {
              approveAllCount.value++;
            }

            if (voucher.user_id) {
              userInfo.value = users?.value?.find(
                (user) => user.user_id === voucher.user_id
              );

              if (voucher.user_id === userInfo?.value?.user_id) {
                Object.assign(voucher, {
                  email: userInfo?.value?.email,
                  name: userInfo?.value?.name,
                });
              }
            }
          }
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const approveVoucher = (id, approved) => {
      userService
        .approveVoucher(id, approved)
        .then((response) => {
          toast.value.toast(response.data.msg, "#388E3C");
          getVouchers();
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const approveAllVouchers = () => {
      userService
        .approveAllVouchers()
        .then((response) => {
          toast.value.toast(response.data.msg, "#388E3C");
          getVouchers();
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const getUsers = () => {
      userService
        .getUsers()
        .then((response) => {
          const { data } = response.data;
          users.value = data;
          users.value.map((usedData) => {
            usedResources.value += usedData.used_vms;
            usedIPs.value += usedData.used_public_ips;
          });
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const usersPerPage = computed(() => {
      return vouchers.value.slice(
        (currentPage.value - 1) * itemsPerPage.value,
        currentPage.value * itemsPerPage.value
      );
    });

    const addAvatar = (name) => {
      return name.charAt(0);
    };

    onMounted(() => {
      let token = localStorage.getItem("token");
      if (token) {
        getUsers();
        getVouchers();
      }
    });

    return {
      vouchersHeaders,
      vouchers,
      usedResources,
      approveAllCount,
      usersHeaders,
      users,
      userInfo,
      loading,
      confirm,
      toast,
      usersPerPage,
      getVouchers,
      approveVoucher,
      approveAllVouchers,
      getUsers,
      addAvatar,
      currentPage,
      totalPages,
      itemsPerPage,
      usedIPs,
    };
  },
  beforeRouteEnter(to, from, next) {
    userService
      .getUser()
      .then((response) => {
        const { user } = response.data.data;
        const isAdmin = user.admin;
        if (isAdmin) {
          next();
        } else {
          next("/");
        }
      })
      .catch((response) => {
        console.log(response);
      });
  },
};
</script>

<style>
.resources {
  margin-top: 0.5rem;
}

td {
  line-height: 1em;
}
.actions {
  position: relative;
}

.approve {
  position: absolute;
  right: 5px;
}

.shadow {
  box-shadow: 0px 2px 4px 2px rgba(0, 0, 0, 0.1);
}
</style>
