<template>
  <v-container style="max-width: 1700px;" fill-height>
    <h5 class="text-h5 text-md-h4 font-weight-bold text-center my-10 secondary">
      Admin Panel
    </h5>
    <v-row>
      <v-col cols="12" md="8">
        <div class="actions d-flex justify-end my-2">
          <BaseButton
            :disabled="approveAllCount <= 0"
            color="primary"
            text="Approve All"
            class="approve text-capitalize"
            @click="approveAllVouchers"
          />
        </div>
        <v-data-table
          :headers="vouchersHeaders"
          :items="vouchers"
          class="elevation-1 rounded shadow"
        >
          <template v-slot:item="{ item }">
            <tr>
              <td>{{ item.raw.id }}</td>
              <td v-if="item.raw.name" class="d-flex align-center">
                <v-avatar color="primary" size="30" class="mr-2">
                  <span class="text-uppercase">{{
                    addAvatar(item.raw.name)
                  }}</span>
                </v-avatar>
                <div>
                  <p>{{ item.raw.name }}</p>
                  <p>
                    {{ item.raw.email }}
                  </p>
                </div>
              </td>

              <td class="d-flex align-center" v-else>
                <v-avatar color="warning" size="30" class="mr-2">
                  <span class="text-uppercase">A</span>
                </v-avatar>
                <div>
                  <p>Voucher generated by Admin</p>
                </div>
              </td>
              <td v-if="item.columns.reason">{{ item.columns.reason }}</td>
              <td v-else>-</td>
              <td>{{ item.columns.vms }}</td>
              <td>{{ item.columns.public_ips }}</td>
              <td
                v-if="!item.props.title.approved && !item.props.title.rejected"
              >
                <BaseButton
                  color="primary"
                  text="Approve"
                  size="small"
                  class="mr-2 text-capitalize"
                  variant="flat"
                  @click="approveVoucher(item.columns.id, true)"
                />

                <BaseButton
                  color="red-lighten-1"
                  text="Reject"
                  size="small"
                  class="text-capitalize"
                  variant="flat"
                  @click="approveVoucher(item.columns.id, false)"
                />
              </td>
              <td v-else-if="item.raw.rejected">
                <span class="text-error">Rejected</span>
              </td>
              <td v-else>
                <span class="text-success">Approved</span>
              </td>
            </tr>
          </template>
        </v-data-table>
      </v-col>
      <v-col cols="12" md="4">
        <v-row>
          <v-col>
            <div
              class="resources text-white text-center rounded-lg bg-primary py-5 shadow"
            >
              <p>
                <strong style="font-size: 2.5rem;">{{ usedResources }}</strong>
              </p>
              <p class="mx-lg-auto font-weight-medium">
                Used VMs
              </p>
            </div>
          </v-col>
          <v-col>
            <div
              class="resources text-white text-center rounded-lg bg-primary py-5 shadow"
            >
              <p>
                <strong style="font-size: 2.5rem;">{{ usedIPs }}</strong>
              </p>
              <p class="mx-lg-auto font-weight-medium">
                Used IPs
              </p>
            </div>
          </v-col>
        </v-row>
        <section class="my-5 shadow">
          <h5 class="bg-grey-lighten-5 text-h5 bg-primary text-center pa-4">
            Users
          </h5>
          <v-data-table
            v-model:items-per-page="itemsPerPage"
            :headers="usersHeaders"
            :items="users"
            class="elevation-1"
          >
            <template v-slot:item="{ item, index }">
              <tr>
                <td>
                  {{ ++index }}
                </td>
                <td v-if="item.columns.name" class="d-flex align-center">
                  <v-avatar color="primary" size="30" class="mr-2">
                    <span class="text-uppercase">{{
                      addAvatar(item.columns.name)
                    }}</span>
                  </v-avatar>
                  <div>
                    <p>{{ item.columns.name }}</p>
                    <p>
                      {{ item.raw.email }}
                    </p>
                  </div>
                </td>
                <td>
                  <span class="text-red">{{ item.raw.used_vms }}</span>
                  /<span>{{ item.columns.vms }}</span>
                </td>
                <td>
                  <span class="text-red">{{ item.raw.used_public_ips }}</span
                  >/<span>{{ item.columns.public_ips }}</span>
                </td>
              </tr>
            </template>
          </v-data-table>
        </section>
      </v-col>
    </v-row>
    <Toast ref="toast" />
  </v-container>
</template>

<script>
import { ref, onMounted } from "vue";
import BaseButton from "@/components/Form/BaseButton.vue";
import userService from "@/services/userService.js";
import Toast from "@/components/Toast.vue";

export default {
  components: {
    BaseButton,
    Toast,
  },
  setup() {
    const confirm = ref(null);
    const vouchersHeaders = ref([
      { title: "No", key: "id" },
      { title: "User", key: "user", sortable: false },
      { title: "Reason for Voucher", key: "reason", sortable: false },
      { title: "VMs", key: "vms" },
      { title: "Public IPs", key: "public_ips" },
      { title: "Actions", key: "actions", sortable: false },
    ]);

    const usersHeaders = ref([
      { title: "No", key: "id", sortable: false },
      { title: "Name", key: "name", sortable: false },
      { title: "VMs", key: "vms", sortable: false },
      { title: "IPs", key: "public_ips", sortable: false },
    ]);

    const vouchers = ref([]);
    const users = ref([]);
    const toast = ref(null);
    const loading = ref(false);
    const usedResources = ref(null);
    const usedIPs = ref(null);
    const approveAllCount = ref(null);
    const userInfo = ref(null);
    const itemsPerPage = ref(5);
    const getVouchers = () => {
      userService
        .getVouchers()
        .then((response) => {
          const { data } = response.data;
          approveAllCount.value = 0;

          for (let voucher of data) {
            if (!voucher?.approved && !voucher?.rejected) {
              approveAllCount.value++;
            }

            if (voucher.user_id) {
              userInfo.value = users?.value?.find(
                (user) => user.user_id === voucher.user_id
              );
              if (voucher.user_id === userInfo?.value?.user_id) {
                Object.assign(voucher, {
                  email: userInfo?.value?.email,
                  name: userInfo?.value?.name,
                });
              }
            }
          }

          vouchers.value = data;
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const approveVoucher = (id, approved) => {
      userService
        .approveVoucher(id, approved)
        .then((response) => {
          toast.value.toast(response.data.msg, "#388E3C");
          getVouchers();
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const approveAllVouchers = () => {
      userService
        .approveAllVouchers()
        .then((response) => {
          toast.value.toast(response.data.msg, "#388E3C");
          getVouchers();
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const getUsers = () => {
      userService
        .getUsers()
        .then((response) => {
          const { data } = response.data;
          users.value = data;
          users.value.map((usedData) => {
            usedResources.value += usedData.used_vms;
            usedIPs.value += usedData.used_public_ips;
          });
        })
        .catch((response) => {
          const { err } = response.response.data;
          toast.value.toast(err, "#FF5252");
        });
    };

    const addAvatar = (name) => {
      return name.charAt(0);
    };

    onMounted(() => {
      let token = localStorage.getItem("token");
      if (token) {
        getUsers();
        getVouchers();
      }
    });

    return {
      vouchersHeaders,
      vouchers,
      usedResources,
      approveAllCount,
      usersHeaders,
      users,
      userInfo,
      loading,
      confirm,
      toast,
      itemsPerPage,
      getVouchers,
      approveVoucher,
      approveAllVouchers,
      getUsers,
      addAvatar,
      usedIPs,
    };
  },
  beforeRouteEnter(to, from, next) {
    userService
      .getUser()
      .then((response) => {
        const { user } = response.data.data;
        const isAdmin = user.admin;
        if (isAdmin) {
          next();
        } else {
          next("/");
        }
      })
      .catch((err) => {
        console.log(err);
      });
  },
};
</script>

<style>
.resources {
  margin-top: 0.5rem;
}

td {
  line-height: 1em;
}

.shadow {
  box-shadow: 0px 2px 4px 2px rgba(0, 0, 0, 0.1);
}
</style>
